Repository GEOS-ESM/GEOSldas, pull requests merged in 2020-07, with the labels that each got.

#267 bug fix typo for $LEN_ in monthly-mean post-processing (lenkf.j.template)
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff, bug fix

#269 documentation updates (8 Jul 2020)
  README.md
  doc/CHANGELOG.md
  doc/README.metforcing_and_bcs.md
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_routines.F90
Labels: 0-diff trivial, documentation

#274 Clean up black/white terminology
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/preprocess_ldas.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordRoutines.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_functions.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_init_routines.F90
Labels: 0-diff, cleanup

#273 correcting metadata field name for Rainf in tile_bin2nc4.F90
  src/Applications/LDAS_App/tile_bin2nc4.F90
Labels: 0-diff trivial, bug fix, documentation

#275 Bugfix: catparam file with NLv4 bcs
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_init_routines.F90
Labels: 0-diff, bug fix

#277 bug fix: convert lat/lon (centerY/centerX) for EASE tiles to radians before use in ESMF
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
Labels: 0-diff trivial, bug fix

#278 switch order of pert_grid_f and pert_grid_l in LDASsa_get_pert()
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/land_pert.F90
Labels: 0-diff, cleanup

#279 Bugfix/check current time
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
Labels: 0-diff, bug fix

#280 extract fill values from .ctl file
  src/Applications/LDAS_App/tile_bin2nc4.F90
Labels: 0-diff trivial, enhancement

#281 write lmc with mwrtm no matter landassim status
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
Labels: 0-diff, enhancement
