Repository GEOS-ESM/GEOSldas, pull requests merged in 2020-04, with the labels that each got.

#160 New Surface parameter resource file
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
Labels: Not 0-diff, infrastructure

#167 README.md update for SLES12
  README.md
Labels: 0-diff trivial, documentation

#169 bug fix for pertseed restart from an existing run
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff, bug

#170 clarified compute node requirement for SLES12
  README.md
Labels: 0-diff trivial, documentation

#171 bug fix: removed indent that broke subdaily2daily
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff trivial, bug

#172 Merging develop into master
  Externals.cfg
  README.md
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/process_rst.csh
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
Labels: Not 0-diff

#178 fix gnu debug
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_HashTable.F90
Labels: 0-diff, bug

#181 night tests on sles12
  Externals.cfg
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/process_rst.csh
Labels: 0-diff

#185 updating to MAPL 2.1.1
  Externals.cfg
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
Labels: 0-diff, infrastructure

#186 Syncing develop into feature branch
  Externals.cfg
  src/Applications/LDAS_App/ldas_setup
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
Labels: 0-diff

#197 Use EMSA_env v2.1.1+intel19.1.0
  Externals.cfg
Labels: Not 0-diff, infrastructure

#199 cleanup of obsolete LDASsa code
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_drv_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_out_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_DriverTypes.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_init_routines.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
Labels: 0-diff, cleanup

#200 hotfix for subdaily2daily nc4 file concatenation (post-proc)
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff, hotfix, post-processing
