Repository GEOS-ESM/GEOSldas, pull requests merged in 2020-11, with the labels that each got.

#331 New ESMA_env 3.1.0
  Externals.cfg
  components.yaml
Labels: 0-diff

#335 Remove support for manage_externals
  Externals.cfg
  README.md
  parallel_build.csh
Labels: 0-diff, cleanup, documentation, infrastructure

#333 corrected help text with location of README file
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff trivial, documentation
