Repository GEOS-ESM/GEOSldas, pull requests merged in 2020-12, with the labels that each got.

#337 Update to MAPL 2.4.0
  components.yaml
Labels: 0-diff

#340 Soil temperatures (TP's) EXPORT variables in units of Kelvin throughout
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_routines.F90
Labels: Not 0-diff

#341 Feature/wjiang/output_incr
  src/Applications/LDAS_App/util/average_ensemble_forcing.py
  src/Applications/LDAS_App/util/generate_catchincr_hist.py
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOSexportcatchincr_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOSexportcatchincr_GridComp/GEOS_ExportCatchIncrGridComp.F90
Labels: 0-diff, enhancement

#345 check cs forcing dimension
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
Labels: 0-diff, consistency check
