Repository GEOS-ESM/GEOSldas, pull requests merged in 2020-08, with the labels that each got.

#286 Updated documentation (README.metforcing_and_bcs)
  doc/README.metforcing_and_bcs.md
Labels: 0-diff trivial, documentation

#290 character in nml file should include quote
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff, bug fix, pre-processing

#282 no monthy or daily if ref_time is not '000000'
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff

#295 Feature/use_hash_indg
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_adapt_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordRoutines.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
Labels: 0-diff, cleanup

#299 Update CHANGELOG.md
  doc/CHANGELOG.md
Labels: 0-diff trivial, documentation
