Repository GEOS-ESM/GEOSldas, pull requests merged in 2021-05, with the labels that each got.

#377 Adding ERA5 as Met Forcing option
  doc/README.MetForcing_and_BCS.md
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
Labels: 0-diff, enhancement

#402 Update gitignore for mepo update
  .gitignore
  src/Components/GEOSldas_GridComp/.gitignore
  src/Shared/.gitignore
Labels: 0-diff trivial

#397 remove dtstep_assim and centered_update from nml
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
Labels: 0-diff

#404 replaced "dtstep_assim" and "centered_update" with "LANDASSIM_DT" and "LANDASSIM_T0"
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
Labels: 0-diff, cleanup, enhancement

#392 use assim alarm for centered_update option
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
Labels: 0-diff, enhancement

#381 add options to use output server for restart and history
  CMakeLists.txt
  components.yaml
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
Labels: 0-diff, enhancement

#406 use v2.6.8 of MAPL
  components.yaml
Labels: 0-diff

#384 Updates needed for NAG
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/io_hdf5.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/catch_types.F90
Labels: 0-diff

#407 Updates for MAPL 2.7.0
  components.yaml
  src/Applications/LDAS_App/GEOSldas.F90
Labels: 0-diff

#408 updated doc: CHANGELOG.md (v17.9.3), ldas_setup (resource manager)
  doc/CHANGELOG.md
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff trivial, documentation

#409 merge "develop" into "BRIDGE" in prep for v17.9.3
  .gitignore
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  components.yaml
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
  src/Applications/LDAS_App/GEOSldas.F90
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Applications/LDAS_App/util/read_obslog.m
  src/Components/GEOSldas_GridComp/.gitignore
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/io_hdf5.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/LDAS_PertRoutines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/land_pert.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Interp.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_DriverTypes.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_RepairForcing.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/Shared/catch_types.F90
  src/Components/GEOSldas_GridComp/Shared/my_matrix_functions.F90
  src/Shared/.gitignore
Labels: 0-diff, Contingent -- Do Not Approve

#410 Merge BRIDGE into main in prep for v17.9.3
  .gitignore
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  components.yaml
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
  src/Applications/LDAS_App/GEOSldas.F90
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Applications/LDAS_App/util/read_obslog.m
  src/Components/GEOSldas_GridComp/.gitignore
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/io_hdf5.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/LDAS_PertRoutines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/land_pert.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Interp.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_DriverTypes.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_RepairForcing.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/Shared/catch_types.F90
  src/Components/GEOSldas_GridComp/Shared/my_matrix_functions.F90
  src/Shared/.gitignore
Labels: 0-diff
