Repository GEOS-ESM/GEOSldas, pull requests merged in 2021-11, with the labels that each got.

#481 enforce IMS >=2
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
Labels: 0-diff

#482 Add automatic PR for develop to MAPL3 branch
  .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
  .github/workflows/push-to-develop.yml
Labels: 0-diff trivial

#484 MAPL V3 FLAP Simplification
  components.yaml
  src/Applications/LDAS_App/GEOSldas.F90
Labels: 0-diff, MAPL3
