Repository GEOS-ESM/GEOSldas, pull requests merged in 2021-09, with the labels that each got.

#444 Update ESMA_cmake to v3.5.5, update CI and CMakeLists.txt
  .circleci/config.yml
  CMakeLists.txt
  components.yaml
Labels: 0-diff

#445 convert NUM_SGMT to int
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff trivial, bug fix

#446 update MAPL for shave bit function
  components.yaml
Labels: enhancement, 0-diff

#447 Updated CHANGELOG.md in prep for release v17.9.5
  doc/CHANGELOG.md
Labels: documentation, 0-diff trivial

#448 Merge BRIDGE into main in prep for release v17.9.5
  .circleci/config.yml
  CMakeLists.txt
  LICENSE.md
  components.yaml
  doc/CHANGELOG.md
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
Labels: 0-diff

#449 Add auto tarball script
  .github/workflows/release-tarball.yml
Labels: 0-diff trivial

#451 Update GEOSldas version info in CMakeLists.txt
  CMakeLists.txt
Labels: 0-diff trivial, bug fix

#452 change local name to avoid ambiguity and pass GNU build
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_out_routines.F90
Labels: 0-diff, bug fix

#454 Update LICENSE to Apache, other license changes
  COPYRIGHT
  LICENSE
  LICENSE-NOSA
  README.md
Labels: documentation, 0-diff trivial

#455 Fix license reference in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, 0-diff trivial

#456 Update CHANGELOG.md in prep for release v17.9.6
  doc/CHANGELOG.md
Labels: 0-diff trivial

#460 Updated CHANGELOG.md: edited license change info
  doc/CHANGELOG.md
Labels: 0-diff trivial
