Repository GEOS-ESM/GEOSldas, pull requests merged in 2021-10, with the labels that each got.

#326 Updates to support Catchment-CN.4.0 and Catchment-CN.4.5
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/mk_GEOSldasRestarts.F90
  src/Applications/LDAS_App/process_hist.csh
  src/Applications/LDAS_App/process_rst.csh
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
Labels: Not 0-diff

#465 Make bit shaving default in HISTORY template
  src/Applications/LDAS_App/GEOSldas_HIST.rc
Labels: documentation, Not 0-diff, 0-diff, output

#475 fix ldas_setup from one subdomain member to multiple members
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff trivial, bug fix

#474 when LADAS_COUP =1, (1) copy $FVWORK/forcing files to scratch/ (2) make forc path to scratch/
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff trivial, bug fix
