Repository GEOS-ESM/GEOSldas, pull requests merged in 2022-09, with the labels that each got.

#569 Reorg of LDAS_App and additional LADAS-related utilities
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/README_LDAS_App
  src/Applications/LDAS_App/ens_forcing/average_ensemble_forcing.py
  src/Applications/LDAS_App/ens_forcing/enpert_forc.csh
  src/Applications/LDAS_App/ens_forcing/ensemble_forc.py
  src/Applications/LDAS_App/ens_forcing/regrid_forc.csh
  src/Applications/LDAS_App/ens_forcing/test_enpert_forc.j
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/sample_config_files/LADAS/HISTORY.rc.atmens
  src/Applications/LDAS_App/sample_config_files/LADAS/HISTORY.rc.central
  src/Applications/LDAS_App/sample_config_files/LADAS/exeinp.txt.Hy4dEnVar.atmens
  src/Applications/LDAS_App/sample_config_files/LADAS/exeinp.txt.Hy4dEnVar.central
  src/Applications/LDAS_App/util/config/Create_ccorr_cat_progn_default.m
  src/Applications/LDAS_App/util/config/generate_catchincr_hist.py
  src/Applications/LDAS_App/util/inputs/mwRTM_params/Create_mwRTM_param_file.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/Create_vegopacity_8day_clim.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/Preprocess_L2DCA_mwRTM_params_to_dailymat.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/fill_gaps_in_tiledata.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_L2_RTM_constants_tile_data.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_mwRTM_lookup.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_mwRTM_vegcls_based.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/mwrtm_bin2nc4.F90
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/Run_get_L4_Tb_scale_SMAP.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/dist_km2deg.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_ij_ind_from_latlon.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_model_and_obs_clim_stats.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_tile_num_for_obs.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_tile_num_in_cell_ij.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/write_seqbin_file.m
  src/Applications/LDAS_App/util/postproc/climatology/README
  src/Applications/LDAS_App/util/postproc/climatology/Run_L4_sm_clim_stats.m
  src/Applications/LDAS_App/util/postproc/climatology/Write_L4_sm_clim_stat_bin2nc4.m
  src/Applications/LDAS_App/util/postproc/climatology/get_model_clim_stats.m
  src/Applications/LDAS_App/util/postproc/climatology/read_seqbin_clim_pctl_file.m
  src/Applications/LDAS_App/util/postproc/climatology/write_seqbin_clim_pctl_file.m
  src/Applications/LDAS_App/util/postproc/compress_bit-shaved_nc4.sh
  src/Applications/LDAS_App/util/postproc/write_smapL4SMqa.m
  src/Applications/LDAS_App/util/shared/matlab/J2000_to_DateTime.m
  src/Applications/LDAS_App/util/shared/matlab/MAPL_ReadForcing_fullfile.m
  src/Applications/LDAS_App/util/shared/matlab/augment_date_time.m
  src/Applications/LDAS_App/util/shared/matlab/days_in_month.m
  src/Applications/LDAS_App/util/shared/matlab/get_dofyr_pentad.m
  src/Applications/LDAS_App/util/shared/matlab/is_leap_year.m
  src/Applications/LDAS_App/util/shared/matlab/read_ObsFcstAna.m
  src/Applications/LDAS_App/util/shared/matlab/read_catparam.m
  src/Applications/LDAS_App/util/shared/matlab/read_obslog.m
  src/Applications/LDAS_App/util/shared/matlab/read_obsparam.m
  src/Applications/LDAS_App/util/shared/matlab/read_smapL4SMaup.m
  src/Applications/LDAS_App/util/shared/matlab/read_smapL4SMlmc.m
  src/Applications/LDAS_App/util/shared/matlab/read_tilecoord.m
  src/Applications/LDAS_App/util/shared/matlab/read_tilegrids.m
  src/Applications/LDAS_App/util/shared/matlab/tile2grid.m
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_types.F90
Labels: enhancement, 0-diff, cleanup, post-processing, pre-processing

#574 fix character length in declaration of string variables to avoid truncation of file paths/names
  src/Applications/LDAS_App/preprocess_ldas.F90
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Applications/LDAS_App/util/inputs/mwRTM_params/mwrtm_bin2nc4.F90
Labels: 0-diff, cleanup, bug fix

#551 Clean up mk_GEOSldasRestarts and process_rst.csh
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/process_rst.csh
  src/Applications/LDAS_App/process_rst.py
Labels: 0-diff, cleanup

#578 Update to MAPL 2.25.0
  components.yaml
Labels: 0-diff, bug fix

#579 Update to ESMA_env 4.4.0 and ESMA_cmake v3.18.0
  .editorconfig
  .gitignore
  CMakePresets.json
  components.yaml
Labels: 0-diff, infrastructure
