Repository GEOS-ESM/GEOSldas, pull requests merged in 2022-02, with the labels that each got.

#517 GEOSldas changes prompted by cleanup of catch_constants in GEOSgcm GC
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_drv_routines.F90
  src/Components/GEOSldas_GridComp/Shared/CMakeLists.txt
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/Shared/catch_types.F90
Labels: 0-diff, cleanup

#523 change MAPL_ENABLE_BOOTSTRAP to YES
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
Labels: 0-diff trivial

#515 new peat hydrology (PEATCLSM)
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_drv_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensdrv_out_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
Labels: enhancement, 0-diff

#453 Add ensemble forcing functionality
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/GEOS_MetforceGridComp.F90
Labels: enhancement, 0-diff

#526 Script to compress bit-shaved netcdf output
  doc/README.OutputSpecs.md
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/util/compress_bit-shaved_nc4.sh
Labels: 0-diff trivial, post-processing

#531 bug fix: dimensions of WATERTABLED export in GEOS_EnsGridComp.F90 (MAPL_DimsTileOnly)
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
Labels: 0-diff, bug fix

#529 modified EnKF update_type 10 for PEATCLSM (include catdef in EnKF State)
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_bias_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
Labels: enhancement, 0-diff
