Repository GEOS-ESM/GEOSldas, pull requests merged in 2022-01, with the labels that each got.

#503 Compress CircleCI Artifacts
  .circleci/config.yml
Labels: 0-diff trivial

#506 Update to MAPL v2.15.0, remove EXPDSC: and EXPSRC: from GEOSldas_HIST.rc
  components.yaml
  src/Applications/LDAS_App/GEOSldas_HIST.rc
Labels: 0-diff, cleanup

#505 remove catchincr grid comp when it is not land_assim
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
Labels: 0-diff, bug fix

#511 Updated README.metforcing_and_bcs for SMAP L4_SM Version 6
  doc/README.MetForcing_and_BCS.md
Labels: documentation, 0-diff trivial

#514 Remove GEOSldas version info from CMakeLists.txt
  CMakeLists.txt
Labels: 0-diff, cleanup

#516 Added dummy GEOSldas version to CMakeLists.txt
  CMakeLists.txt
Labels: 0-diff trivial, cleanup

#518 no shell for subprocess call
  README.md
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff
