Repository GEOS-ESM/GEOSldas, pull requests merged in 2023-12, with the labels that each got.

#681 Update Repositories
  .circleci/config.yml
  README.md
  components.yaml
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff

#685 Remove requirement for mwRTM parameter files inputs
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
Labels: 0-diff, bug fix

#656 Adding ASCAT SM reader and matlab util for clim_stats
  components.yaml
  config/NCEP_Shared.sparse
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/util/inputs/mwRTM_params/Create_vegopacity_8day_clim.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_L2_RTM_constants_tile_data.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/Run_get_model_and_obs_clim_stats_latlon_grid.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_model_and_obs_clim_stats.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_model_and_obs_clim_stats_latlon_grid.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_tile_num_for_obs.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/write_netcdf_latlon_grid.m
  src/Applications/LDAS_App/util/postproc/climatology/get_model_clim_stats.m
  src/Applications/LDAS_App/util/postproc/write_smapL4SMqa.m
  src/Applications/LDAS_App/util/shared/matlab/pentad_of_year.m
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_glob_param.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/Shared/enkf_types.F90
  src/Shared/.gitignore
  src/Shared/CMakeLists.txt
Labels: enhancement, 0-diff, matlab utils
