Repository GEOS-ESM/GEOSldas, pull requests merged in 2023-05, with the labels that each got.

#644 Add Mironov soil dielectric mixing model and rough reflectivity parameter options
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_routines.F90
Labels: enhancement, 0-diff

#646 Updates in prep for GEOSldas release v17.13.0: ESMA_env v4.9.1, ESMA_cmake v3.28.0, GMAO_Shared v1.9.0, GEOS_Util v2.0.0, MAPL v2.39.1, CHANGELOG.md
  components.yaml
  doc/CHANGELOG.md
Labels: documentation, 0-diff, infrastructure

#649 Merge BRIDGE into main in prep for GEOSldas release v17.13.0
  .github/workflows/enforce-labels.yml
  components.yaml
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
  src/Applications/LDAS_App/GEOSldas_HIST.rc
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
  src/Applications/LDAS_App/process_rst.py
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Applications/LDAS_App/util/inputs/mwRTM_params/Create_vegopacity_8day_clim.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_L2_RTM_constants_tile_data.m
  src/Applications/LDAS_App/util/inputs/mwRTM_params/get_mwRTM_vegcls_based.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_ij_ind_from_latlon.m
  src/Applications/LDAS_App/util/inputs/obs_scaling_params/get_model_and_obs_clim_stats.m
  src/Applications/LDAS_App/util/postproc/write_smapL4SMqa.m
  src/Applications/LDAS_App/util/shared/matlab/EASEv2_ind2latlon.m
  src/Applications/LDAS_App/util/shared/matlab/EASEv2_latlon2ind.m
  src/Components/GEOSldas_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOS_LdasGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSens_GridComp/GEOS_EnsGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_adapt_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/mwRTM_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/LDAS_PertRoutines.F90
  src/Components/GEOSldas_GridComp/Shared/CMakeLists.txt
  src/Components/GEOSldas_GridComp/Shared/LDAS_DateTimeMod.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_PertTypes.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordRoutines.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/Shared/catch_types.F90
  src/Shared/CMakeLists.txt
Labels: 0-diff

#650 fix error in CHANGELOG.md in prep for GEOSldas release v17.13.0
  doc/CHANGELOG.md
Labels: documentation, 0-diff

#652 Re-merge BRIDGE into main after fixing error in CHANGELOG.md in prep for GEOSldas release v17.13.0
  doc/CHANGELOG.md
Labels: documentation, 0-diff
