Repository GEOS-ESM/GEOSldas, pull requests merged in 2024-02, with the labels that each got.

#700 Update to ESMA_cmake v3.40.0
  components.yaml
Labels: 0-diff

#693 Make GEOSldas work for SLES15 / Milan
  README.md
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff

#698 update generate_catchincr_hist.py and LADAS sample documents
  src/Applications/LDAS_App/sample_config_files/LADAS/HISTORY.rc.atmens
  src/Applications/LDAS_App/sample_config_files/LADAS/exeinp.txt.Hy4dEnVar.central
  src/Applications/LDAS_App/util/config/generate_catchincr_hist.py
Labels: documentation, 0-diff trivial, pre-processing

#707 Disable Catchment-CN4.5 land model choice in GEOSldas
  components.yaml
  src/Applications/LDAS_App/GEOSldas_LDAS.rc
  src/Applications/LDAS_App/ldas_setup
Labels: 0-diff

#710 Fix error in components.yaml of #707
  components.yaml
Labels: 0-diff trivial, urgent, bug fix

#714 rename GEOSldas_GridComp/Shared to GEOSldas_GridComp/LDAS_Shared
  src/Components/GEOSldas_GridComp/CMakeLists.txt
  src/Components/GEOSldas_GridComp/LDAS_Shared/CMakeLists.txt
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_Convert.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_DriverTypes.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_Exceptions.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_PertTypes.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_RepairForcing.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_TileCoordRoutines.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_TileCoordType.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_ensdrv_Globals.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_ensdrv_functions.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/catch_types.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/enkf_types.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/my_lu_decomp.f
  src/Components/GEOSldas_GridComp/LDAS_Shared/my_matrix_functions.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/nr_indexx.f
Labels: 0-diff

#680 adapt to new bcs structure
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/remap_config_ldas.py
Labels: 0-diff

#711 sparse checkout of GEOS_util
  components.yaml
  config/GEOS_Util.sparse
Labels: 0-diff

#706 support NAS site
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
Labels: enhancement, 0-diff

#718 support reading corrected precipitation from aggregated daily netcdf files
  src/Components/GEOSldas_GridComp/GEOSmetforce_GridComp/LDAS_Forcing.F90
Labels: 0-diff

#703 Add "update_type" for joint assimilation of ASCAT SM and SMAP Tb
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
Labels: enhancement, 0-diff

#723 Read and apply mask during ASCAT QC
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/util/shared/matlab/read_obsparam.m
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/LDAS_ensdrv_mpi.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/enkf_types.F90
Labels: enhancement, 0-diff
