Repository GEOS-ESM/GEOSldas, pull requests merged in 2024-03, with the labels that each got.

#512 MODIS snow cover fraction assimilation
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/tile_bin2nc4.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_glob_param.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90
  src/Components/GEOSldas_GridComp/LDAS_Shared/enkf_types.F90
Labels: enhancement, 0-diff

#725 Update utilities versions (components.yaml)
  components.yaml
Labels: 0-diff

#730 Point to GEOSgcm_GridComp branch with non-0-diff snow model fixes
  components.yaml
Labels: Not 0-diff

#729 ASCAT mask maker input utility program
  src/Applications/LDAS_App/CMakeLists.txt
  src/Applications/LDAS_App/LDASsa_DEFAULT_inputs_ensupd.nml
  src/Applications/LDAS_App/util/inputs/ASCAT_sm_mask/CMakeLists.txt
  src/Applications/LDAS_App/util/inputs/ASCAT_sm_mask/ascat_mask_maker.F90
Labels: 0-diff trivial

#732 reverting to "develop" branch for GEOSgcm_GridComp (components.yaml)
  components.yaml
Labels: 0-diff

#734 Update to MAPL v2.44.1 to fix "binary + bit shaving" bug
  components.yaml
Labels: Not 0-diff

#733 Allow users to setup a GEOSldas experiment from somebody else's build
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/preprocess_ldas.F90
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
Labels: 0-diff

#739 Update some GitHub Actions versions
  .github/workflows/push-to-develop.yml
  .github/workflows/release-tarball.yml
Labels: 0-diff trivial

#740 create IMS.rc or JMS.rc directly on run_dir
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/preprocess_ldas.F90
  src/Applications/LDAS_App/preprocess_ldas_routines.F90
Labels: 0-diff

#728 updated documentation in prep for Release v18.0.0
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
Labels: documentation, 0-diff trivial

#745 change relative path in lenkf.j to abs path
  src/Applications/LDAS_App/ldas_setup
  src/Applications/LDAS_App/lenkf.j.template
Labels: 0-diff

#751 updated documentation in prep for release v18.0.1
  README.md
  doc/CHANGELOG.md
Labels: documentation, 0-diff
