Repository GEOS-ESM/GEOSldas, pull requests merged in 2025-04, with the labels that each got.

#796 Update env, cmake, GEOS_Util and MAPL releases in components.yaml & update README.md after decommissioning of SLES12 at NCCS
  .circleci/config.yml
  .github/workflows/release-tarball.yml
  CMakeLists.txt
  CMakePresets.json
  README.md
  components.yaml
  parallel_build.csh
  presets/CMakeDefaultPresets.json
  presets/CMakeNCCSPresets.json
Labels: documentation, Not 0-diff

#800 Add Github Actions CI
  .github/actions/ci-build/action.yml
  .github/workflows/workflow.yml
Labels: 0-diff, infrastructure

#802 updated change log in prep for release v19.0.0
  doc/CHANGELOG.md
Labels: documentation, 0-diff trivial

#804 Merge develop into BRIDGE in prep for release v19.0.0
  .circleci/config.yml
  .github/actions/ci-build/action.yml
  .github/workflows/release-tarball.yml
  .github/workflows/workflow.yml
  CMakeLists.txt
  CMakePresets.json
  README.md
  components.yaml
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
  parallel_build.csh
  presets/CMakeDefaultPresets.json
  presets/CMakeNCCSPresets.json
Labels: 0-diff

#805 Merge BRIDGE into main in prep for release v19.0.0
  .circleci/config.yml
  .github/actions/ci-build/action.yml
  .github/workflows/release-tarball.yml
  .github/workflows/workflow.yml
  CMakeLists.txt
  CMakePresets.json
  README.md
  components.yaml
  doc/CHANGELOG.md
  doc/README.MetForcing_and_BCS.md
  parallel_build.csh
  presets/CMakeDefaultPresets.json
  presets/CMakeNCCSPresets.json
Labels: 0-diff

#809 Update to MAPL 2.55.0, GMAO_Shared 2.0.0, add GMAO_perllib 1.0.0
  CMakeLists.txt
  components.yaml
Labels: 0-diff, infrastructure
